apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaledobject
  labels:
    deploymentName: django-app
spec:
  maxReplicaCount: 12
  scaleTargetRef:
    name: django-app
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus.monitoring:8080
        metricName: process_virtual_memory_bytes
        threshold: '100'
        query: rate(process_virtual_memory_bytes{app='django-app'}[20m])
