apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
  namespace: monitoring
  labels:
    type: local
    app: prometheus-deployment
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /prometheus-data-tmp

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: monitoring
  labels:
    type: local
    app: prometheus-deployment
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  namespace: monitoring
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
